### ISSUE TITLE
Errors on startup.

### ISSUE THREAD

**Issue by sigmaprojects** [Jonah-May-OSS/wyoming-whisper-trt#326]
Tried to give this a test but was immediately hit with an error:

> [06/04/2025-01:16:28] [TRT] [E] createInferBuilder: Error Code 6: API Usage Error (Unable to load library: libnvinfer_builder_resource.so.10.10.0: libnvinfer_builder_resource.so.10.10.0: failed to map segment from shared object)
> 2025-06-04 01:16:28.169665280 [ERROR] __main__: Failed to load Whisper TRT model 'base': pybind11::init(): factory function returned nullptr
> torch2trt is already installed. Skipping setup.
> 2025-06-04 01:16:40.498909952 [DEBUG] Using selector: EpollSelector
> 2025-06-04 01:16:40.500585984 [DEBUG] __main__: Logging has been configured.
> 2025-06-04 01:16:40.500672512 [DEBUG] __main__: Normalized model name: 'base' to 'base'.
> 2025-06-04 01:16:40.500702464 [DEBUG] __main__: Model 'base' is language-specific: False
> 2025-06-04 01:16:40.500809728 [DEBUG] __main__: Ensured download directory exists at '/data'.
> 2025-06-04 01:16:40.500842752 [INFO] __main__: Loading Whisper TRT model 'base'...
> [06/04/2025-01:16:51] [TRT] [E] createInferBuilder: Error Code 6: API Usage Error (Unable to load library: libnvinfer_builder_resource.so.10.10.0: libnvinfer_builder_resource.so.10.10.0: failed to map segment from shared object)
> 2025-06-04 01:16:51.258923520 [ERROR] __main__: Failed to load Whisper TRT model 'base': pybind11::init(): factory function returned nullptr

I have a pretty stock compose, just changed the port:
```
services:
  wyoming-whisper-trt:
    image: captnspdr/wyoming-whisper-trt:latest-amd64
    container_name: wyoming-whisper-trt
    ports:
      - 10400:10300
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

Any idea what I can do to mitigate this error?  I'd love to try this and compare the speed.

Thank you
